
version: 2

models:
  - name: stg_stops
    description: "load raw.src_stops_metadata to stage view"
    columns:
      - name: STOP_ID
        description: "The primary key for this table"
        data_type: bigint
        constraints: 
          - type: primary_key
          - type: not_null
        data_tests:
          - unique
          - not_null

  - name: stg_directions
    description: "load raw.src_directions_metadata to stage view"
    columns:
      - name: id
        constraints:
          - type: primary_key
          - type: not_null
    


  - name: stg_lapi
    description: "load raw.src_lapi_data to stage view"
    columns:
      - name: id
        description: "The primary key for this table"
        constraints:
          - type: primary_key
          - type: not_null
        data_tests:
          - unique
          - not_null
        
